name: Build without test
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '16'
          java-package: jdk
          architecture: x64
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle
      - name: Build
        run: |
          ./gradlew :clean :assemble
          ./gradlew :mirfBrainTumor:clean :mirfBrainTumor:assemble
          ./gradlew :mirf-ms-service:clean :mirf-ms-service:assemble
          ./gradlew :mirfMs:clean :mirfMs:assemble
          ./gradlew :_utils:clean :_utils:assemble
          ./gradlew :block:clean :block:assemble
          ./gradlew :repository:clean :repository:assemble
          ./gradlew :orchestrator:clean :orchestrator:assemble