name: Test
on:
  pull_request:
    branches:
      - main
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          java-package: jdk
          architecture: x64
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle
      - name: Run test
        run: |
          ./gradlew :clean :test
          ./gradlew :mirfBrainTumor:clean :mirfBrainTumor:test
          ./gradlew :mirf-ms-service:clean :mirf-ms-service:test
          ./gradlew :mirfMs:clean :mirfMs:test
          ./gradlew :utils:clean :utils:build
          ./gradlew :block:clean :block:test
#          ./gradlew :orchestrator:clean :orchestrator:test
          ./gradlew :repository:clean :repository:test
      - uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: build/reports
      - name: Cleanup Gradle Cache
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties
